In [11]:
import numpy as np

In [18]:
points_3d = np.array([
    [1,2,3],
    [0,3,2]
])

print(points_3d.ndim)
print(points_3d.shape)

2
(2, 3)


In [25]:
points_3d = np.array([
    [[1,2],[4,3]],
    [[0,3],[5,6]]
])

def describe_nad(ndar):
    print(ndar)
    print(ndar.ndim)
    print(ndar.shape)
    print(ndar.size)
    print(ndar.dtype.name)
    
describe_nad(points_3d)

[[[1 2]
  [4 3]]

 [[0 3]
  [5 6]]]
3
(2, 2, 2)
8
int32


In [27]:
arr = np.array([1,2,3])
describe_nad(arr)

lists = np.array([[1,2,3],[4,5,6,7,8]])
describe_nad(lists)

[1 2 3]
1
(3,)
3
int32
[list([1, 2, 3]) list([4, 5, 6, 7, 8])]
1
(2,)
2
object


In [28]:
zeros = np.zeros((2,3))
describe_nad(zeros)

ones = np.ones((2,3))
describe_nad(ones)

[[0. 0. 0.]
 [0. 0. 0.]]
2
(2, 3)
6
float64
[[1. 1. 1.]
 [1. 1. 1.]]
2
(2, 3)
6
float64


In [29]:
ar0 = np.arange(2,10,0.5)
print(ar0)

[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


lin = np.linspace(0,1,10)
print(lin)

reshap0 = lin.reshap(2,5)
print(reshap0)

In [44]:
lin = np.linspace(0,1,10) 
print(lin)

reshap0 = lin.reshape(5,2) 
print(reshap0)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[0.         0.11111111]
 [0.22222222 0.33333333]
 [0.44444444 0.55555556]
 [0.66666667 0.77777778]
 [0.88888889 1.        ]]


In [39]:
arr = np.array([
    [1,2,4,3],
    [0,3,5,6]
])

flat = arr.ravel()
print(flat)

print(arr)
transpose = arr.T
print(transpose)

[1 2 4 3 0 3 5 6]
[[1 2 4 3]
 [0 3 5 6]]
[[1 0]
 [2 3]
 [4 5]
 [3 6]]


In [46]:
x = np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [48]:
print(f"Single value {x[1,1]}")
print(f"Row value {x[1,:]}")
print(f"Column value {x[:,1]}")
print(f"Row values {x[1:3,1:3]}")

Single value 5
Row value [4 5 6 7]
Column value [ 1  5  9 13]
Row values [[ 5  6]
 [ 9 10]]


In [51]:
A= np.arange(4**3).reshape(4,4,4)
print(A[1:3,1:3,1:3])

[[[21 22]
  [25 26]]

 [[37 38]
  [41 42]]]


In [55]:
a = np.arange(5)
b = np.arange(5,10)

print(a, b)
print(a*b)
print(a>2)

[0 1 2 3 4] [5 6 7 8 9]
[ 0  6 14 24 36]
[False False False  True  True]


In [57]:
A = np.array([
    [1,2],
    [3,4],
    [5,6]
])

B= np.array([
    [2],
    [2]
]
)
print(A @ B)

[[ 6]
 [14]
 [22]]


In [58]:
npa = np.random.normal(size=18).reshape(3,3,2)
print(npa)

[[[ 0.29582384  0.79684243]
  [ 1.341853    1.88858657]
  [ 1.92385999 -0.85020788]]

 [[-1.10068203 -1.31002941]
  [-0.75852777  0.39073697]
  [ 1.15845729  0.10736691]]

 [[-0.16188862 -0.43851888]
  [-0.85814996  0.20212751]
  [ 0.38840603  1.24250181]]]


In [65]:
print(f"Max {npa.max()}")
print(f"Max {npa.max(axis=1)}") ##el axis 2 escoge el maximo entre cada columnag
print(f"Max {npa.max(axis=2)}") ##el axis 2 escoge el maximo entre cada fila
print(f"Max {npa.max(axis=0)}")  ##el axis 0 escoge el maximo entre cada indice

Max 1.9238599947011366
Max [[1.92385999 1.88858657]
 [1.15845729 0.39073697]
 [0.38840603 1.24250181]]
Max [[ 0.79684243  1.88858657  1.92385999]
 [-1.10068203  0.39073697  1.15845729]
 [-0.16188862  0.20212751  1.24250181]]
Max [[0.29582384 0.79684243]
 [1.341853   1.88858657]
 [1.92385999 1.24250181]]
